#!/bin/bash

BASE_PATH="~/src/filtercake.com"
SOURCE="tooling/index.md"
TARGET="tooling/index.html"
TITLE="tooling"

cd $BASE_PATH


touch $TARGET
echo "---" > $TARGET
echo "layout: default" >> $TARGET
echo "title: tooling" >> $TARGET
echo "---" >> $TARGET
echo " " >> $TARGET

redcarpet $SOURCE >> $TARGET

git add $SOURCE
git add $TARGET
git ci -m "updated tooling"
git pull
git push origin master
